channels:
  - conda-forge
dependencies:
  - r-base
  - r-tidyverse
  - r-openxlsx
  - pandas==1.1.1 
  - XlsxWriter==1.3.3 
  - xlrd==1.2.0
  - openpyxl==3.0.7
  # - matplotlib==3.3.1 
  # - seaborn==0.9.0
